variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - docker
#  - deploy
#  - tag

build:
  stage: build
  image: node:13-alpine
  artifacts:
    paths:
      - build/
    expire_in: 30 days

  #  services:
  #    - docker:dind
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm build

docker:
  stage: docker
  image: docker:19.03.1-dind
  services:
    - docker:19.03.1-dind
#  dependencies:
#    - build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/scrymetto/kicker:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/scrymetto/kicker:$CI_COMMIT_SHORT_SHA

#deploy:
#  image: dtzar/helm-kubectl:3.1.1
#  stage: deploy
#  script:
#    - echo $CONFIG_KUBE | base64 -d > kube-config.yaml
#    - helm --kubeconfig kube-config.yaml upgrade --install --set image.tag=$CI_COMMIT_SHORT_SHA kicker-backend ./deploy/backend
#    - kubectl --kubeconfig kube-config.yaml get all

#tagImage:
#  only:
#    - tags
#  image: docker:19.03.1-dind
#  services:
#    - docker:19.03.1-dind
#  stage: tag
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker pull registry.gitlab.com/rabot9ga/kicker-scorerates:$CI_COMMIT_SHORT_SHA
#    - docker tag registry.gitlab.com/rabot9ga/kicker-scorerates:$CI_COMMIT_SHORT_SHA registry.gitlab.com/rabot9ga/kicker-scorerates:release-$CI_COMMIT_REF_NAME
#    - docker push registry.gitlab.com/rabot9ga/kicker-scorerates